# Generated by Django 3.2 on 2023-06-07 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EQTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IQTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('result', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('а', 'а'), ('б', 'б'), ('в', 'в'), ('г', 'г'), ('д', 'д')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('login', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=10, prefix='', primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('eq_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.eqtest')),
                ('iq_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.iqtest')),
            ],
        ),
        migrations.CreateModel(
            name='EQTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.eqtest')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.result')),
            ],
        ),
        migrations.AddField(
            model_name='eqtest',
            name='result',
            field=models.ManyToManyField(through='verification.EQTestResult', to='verification.Result'),
        ),
    ]
